version: "3"

services:

  app:
    build: ./boilerplate/containers/${WEBSERVER}/php${PHP}
    environment:
      - LOG_LEVEL=${APP_LOG_LEVEL}
    volumes:
      - ./www/:/var/www/html
      - ./boilerplate/logs/php:/var/log/php
      - ./boilerplate/logs/app:/log

  nginx:
    build: ./boilerplate/containers/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./boilerplate/logs/nginx/:/var/log/nginx
      - ./www/:/var/www/html
    command: nginx -g "daemon off;"

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    restart: always
    ports:
      - 5000:8080

  mysql:
    build: ./boilerplate/containers/mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_LOCAL_PORT}:3306
    volumes:
      - ./boilerplate/logs/mysql:/var/log/mysql
      - ./boilerplate/data/mysql:/var/lib/mysql #Сохранение файлов таблиц в репозитории
      - ./boilerplate/data/backup:/backup
    restart: always

  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysql
    ports:
      - '${PHPMYADMIN_PORT}:80'
    depends_on:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_HOST=mysql

  mail:
    image: mailhog/mailhog
    command: ["-smtp-bind-addr", "0.0.0.0:25"]
    user: root
    expose:
      - 25
      - 8025
    ports:
      - 8025:8025

  redis:
    image: redis:${REDIS_VERSION}
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
      - ./boilerplate/redis:/data/:rw
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]

  memcached:
    image: memcached:${MEMCACHED_VERSION}
    ports:
      - "${MEMCACHED_HOST_PORT}:11211"
    environment:
       MEMCACHED_CACHE_SIZE: "${MEMCACHED_CACHE_SIZE}"
